### PR TITLE
ES6 module loading further fixes

### PR DESCRIPTION
**Pull request by kofifus**
Further fixes to make CS WADO load via latest chrome ES6 module loading

### CODE REVIEW

**Comment by swederik** [comment]
Thanks!

**Comment by kofifus** [comment]
One improvement I was thinking of is that instead of different files that need to be changed, have one file - `externalImports.js` - like this:

----------------------------------
```

/*
 * When loading sources directly with <script type="module"> use the following:
 *   import * as cornerstone from '../../cornerstone/src/index.js';
 *   import * as cornerstoneMath from '../../cornerstoneMath/src/index.js';
 *   import * as dicomParser from'../../dicomParser/src/index.js';
 */

/*
 *   When loading packaged sources use the following:
*/
import * as cornerstone from 'cornerstone-core'
import * as cornerstoneMath from 'cornerstone-math'
import * as dicomParser from 'dicom-parser';
import $ from 'jquery';

/*
 * For both cases keep:
*/
export { cornerstone, cornerstoneMath, dicomParser, $ };

```
------------------------------------

Then in the various files you'll have:

`import cornerstone from '../externalImports.js';`

This will give a single point of change in each library and will make future solutions easier.

If this is desirable I'm happy to make it

Thx!

**Comment by swederik** [comment]
Yeah sure, I don't see any problem with that

**Comment by kofifus** [comment]
I submitted https://github.com/chafey/cornerstone/pull/171 , https://github.com/chafey/cornerstoneTools/pull/250 and https://github.com/chafey/cornerstoneWADOImageLoader/pull/134

Where should documentation go ?

**Pull request merged**
