### PR TITLE
[DicomFile loader] multiframe loading broken

### PR DESCRIPTION
**Pull request by ghetolay**
So we found out on this [thread](https://groups.google.com/forum/?hl=fr#!topic/cornerstone-platform/3n1oG2jTwc0) that loading multiframe wasn't working. 
Looks like a typo error caused by an evil copy/paste.

I've only made this quick change, **no check, test nor rebuild were done**. (I hesitated between creating an issue or a PR and went for a PR because changes are self explain).

### CODE REVIEW

**Comment by swederik** [comment]
Hi Ghet,

Thanks for the PR! Could you also build using grunt?

Thanks,

Erik

**Comment by ghetolay** [comment]
Did it.

Looking forward for the new structure where build files won't by part of sources anymore !

**Comment by chafey** [comment]
Think i just fixed this in the slew of changes I made in 0.12.0, can you double check?  Thank you for submitting a PR

**Comment by ghetolay** [comment]
I don't material to really test it so I've just review the code.

On loadimage.js it seem you could merge this : 

```javascript
// if the dataset for this url is already loaded, use it
if(cornerstoneWADOImageLoader.dataSetCacheManager.isLoaded(parsedImageId.url)) {
    return loadDataSetFromPromise(cornerstoneWADOImageLoader.dataSetCacheManager.load(parsedImageId.url, loader), imageId, parsedImageId.frame, parsedImageId.url);
}

// if multiframe, load the dataSet via the dataSetCacheManager to keep it in memory
if(parsedImageId.frame !== undefined) {
    return loadDataSetFromPromise(cornerstoneWADOImageLoader.dataSetCacheManager.load(parsedImageId.url, loader), imageId, parsedImageId.frame, parsedImageId.url);
}
```

into this : 

```javascript
// if multiframe or if dataset for this url is already loaded, use it
if(parsedImageId.frame !== undefined ||
 cornerstoneWADOImageLoader.dataSetCacheManager.isLoaded(parsedImageId.url)) {
    return loadDataSetFromPromise(cornerstoneWADOImageLoader.dataSetCacheManager.load(parsedImageId.url, loader), imageId, parsedImageId.frame, parsedImageId.url);
}
```

Also you add a ```decache()``` func to the image object but it's never called. Should the user do it ?
Have you thought about using WeekMap ? I think babel provide polyfill for older browsers (< ie11).

**Comment by chafey** [comment]
Carlos sent me the file via email and I verified it works.  Decache is called by cornerstone.  How do you propose we use WeakMap here?

**Comment by ghetolay** [comment]
Sorry it was late I didn't think it through and do not seems appropriate anymore. 
I was thinking about a WeakMap with image's object as key and dataset as value but obviously we won't be able to load a dataset from an url anymore. Also we can't use url as keys on a WeakMap cause it's a string. 
I Just said that because dataSetCacheManager has the exact same role as a WeakMap : keep value in memory until all keys are freed.

What are the use cases of that cache for non-multiframe image ? I can think about 2 but none make sense to me : 

- Access to the dataset of an image at some point after it was loaded => why not add it directly to image object ?
- Reload of same image => already have a image cache for that 

This was about design, now about code after a second review to loadImage.js it seems you could easily get rid of  ```loadDataSetFromPromise()``` and then ```addDecache()```  functions.

**Comment by swederik** [comment]
Closing this because the multiframe loading was fixed earlier. Thanks for your help!

**Pull request closed without merging**
