### PR TITLE
Fix imports/exports to allow native Es6 modules use

### PR DESCRIPTION
**Pull request by kofifus**
This PR Fixes imports/exports to allow native Es6 modules use.

Also removes JQuery imports which are not needed and not used in the other cornerstone components.

### CODE REVIEW

**Comment by swederik** [comment]
Hey,

I should have merged this earlier, sorry about that. Could you rebase / squash this on top of the latest master? Thanks!

**Comment by kofifus** [comment]
Ok I pulled the latest head, and updated my commit. All ready to merge.

Note that is's not easy (and not that great practice) for me to squash my branch commit. However on your side you just need to click 'confirm squash and merge'

Let me know if anything else is needed.

**Comment by swederik** [comment]
Thanks!

**Comment by adreyfus** [comment]
- we should use an intermediate file jquery.js, as we did for cornerstone and corstoneTools, instead of removing jQuery imports

-
 src/imageLoader/wadouri/getEncapsulatedImageFrame.js try to import ../../dicom-parser.js, which does not exists

- two different methods are used to import dicom-parser: 

metaDataProvider.js and dataSetCacheManager: import 'dicom-parser'

getEncapsulatedImageFrame.js: import '../../dicom-parser.js'

We should choose one.

**Pull request merged**
